/* Companion V3 shared surfaces. The character's combat engine stays authoritative. */
(()=>{'use strict';
const cfg=window.COMPANION_V3;if(!cfg)return;document.body.dataset.v3Character=cfg.id;
const key='companion-v3:'+cfg.id+':'+location.pathname.replace(/index\.html$/,'');
const backup=key+':backup';const base=()=>({schema:1,items:[],notes:'',preview:true,npcs:[],noteTab:'mechanical'});
let data=base(),blocked=false;
try{let raw=localStorage.getItem(key);if(raw)data=validate(JSON.parse(raw));else data.items=structuredClone(cfg.defaultItems||[]);}catch(e){blocked=true;data=base();}
if(cfg.id==='nans'&&!blocked&&!data.nansGearMigration){const ring=(cfg.defaultItems||[]).find(i=>i.name==='Anneau de la Surcharge Furieuse');if(ring&&!data.items.some(i=>i.name===ring.name))data.items.push(structuredClone(ring));data.nansGearMigration=true;try{localStorage.setItem(key,JSON.stringify(data))}catch{}}
function validate(x){if(!x||x.schema!==1||!Array.isArray(x.items)||!Array.isArray(x.npcs)||typeof x.notes!=='string'||typeof x.preview!=='boolean')throw Error('Format de sauvegarde V3 incompatible.');if(x.items.length>300||x.npcs.length>200||x.notes.length>150000)throw Error('Sauvegarde trop volumineuse.');for(const i of x.items){if(!i||typeof i.name!=='string'||i.name.length>160||!Number.isInteger(i.qty)||i.qty<0||i.qty>9999||typeof i.note!=='string'||i.note.length>5000||typeof i.image!=='string'||i.image.length>400000)throw Error('Objet invalide.');}for(const p of x.npcs){if(!p||typeof p.name!=='string'||typeof p.note!=='string'||typeof p.image!=='string'||p.image.length>400000)throw Error('PNJ invalide.');}x.noteTab=['mechanical','notes'].includes(x.noteTab)?x.noteTab:'mechanical';return x;}
function persist(){if(blocked){warn('Sauvegarde illisible conservée : exporte-la avant de remplacer.');return false;}try{localStorage.setItem(key,JSON.stringify(data));queueMicrotask(()=>window.CompanionAPI?.sync());return true;}catch{warn('Stockage indisponible. Exporte ta partie.');return false;}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
const nav=$('nav.tabs');if(!nav)return;
const host=document.createElement('div');host.id='v3-root';host.innerHTML=`<nav class="v3-social-tabs" aria-label="Sections sociales" hidden><button type="button" data-v3-social-go="social">Profil</button><button type="button" data-v3-social-go="inventory">Inventaire</button></nav><section class="v3-panel" id="v3-social" hidden></section><section class="v3-panel" id="v3-inventory" hidden></section><section class="v3-panel" id="v3-notes" hidden></section><div class="v3-dock" aria-label="Navigation du compagnon"><button type="button" data-v3-go="combat">◇<span>Combat</span></button><button type="button" data-v3-go="powers">✦<span>Sorts &amp; pouvoirs</span></button><button type="button" data-v3-go="social">◈<span>Social</span></button><button type="button" data-v3-go="notes">▤<span>Journal</span></button></div><p class="v3-warning" role="alert" hidden></p><input type="file" id="v3-file" accept="application/json,.json" hidden><input type="file" id="v3-image-file" accept="image/*" hidden>`;
const main=$('main')||nav.parentElement;main.appendChild(host);
[['social','Social'],['notes','Journal']].forEach(([id,label])=>{const b=document.createElement('button');b.type='button';b.dataset.v3Tab=id;b.className=(nav.querySelector('button')?.className||'').replace(/\bactive\b/g,'').trim();b.textContent=label;nav.appendChild(b)});
function warn(message){const el=$('.v3-warning');if(!el)return;el.textContent=message;el.hidden=false;}
if(blocked)warn('Sauvegarde V3 illisible : elle est conservée. Utilise « Export brut » pour la récupérer.');
function go(id){const powers=id==='powers';if(id==='combat'||powers)id=cfg.combatTab||'combat';if(['social','inventory','notes'].includes(id)){
 nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.v3Tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));host.querySelectorAll('.v3-panel').forEach(p=>p.hidden=p.id!=='v3-'+id);
 }else{host.querySelectorAll('.v3-panel').forEach(p=>p.hidden=true);let btn=[...nav.querySelectorAll('button')].find(b=>b.dataset.tab===id);btn?.click();}
 host.querySelectorAll('[data-v3-go]').forEach(b=>b.classList.toggle('active',b.dataset.v3Go===id||(['social','inventory'].includes(id)&&b.dataset.v3Go==='social')||(id===(cfg.combatTab||'combat')&&b.dataset.v3Go===(powers?'powers':'combat'))));
 const socialTabs=$('.v3-social-tabs');socialTabs.hidden=!['social','inventory'].includes(id);socialTabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.v3SocialGo===id));
 if(cfg.id==='nans'&&id===(cfg.combatTab||'combat'))document.querySelector(`[data-combat-tab="${powers?'resources':'attacks'}"]`)?.click();
 else document.querySelector(`[data-combat-subtab="${powers?'resources':'offense'}"]`)?.click();
 if(id==='social')renderSocial();if(id==='inventory')renderItems();if(id==='notes')renderNotes();
 window.scrollTo({top:0,behavior:'instant'});
}
nav.addEventListener('click',e=>{let b=e.target.closest('[data-v3-tab]');if(b)go(b.dataset.v3Tab);else{const native=e.target.closest('[data-tab]');if(native){$('.v3-social-tabs').hidden=true;host.querySelectorAll('.v3-panel').forEach(p=>p.hidden=true);host.querySelectorAll('[data-v3-go]').forEach(x=>x.classList.toggle('active',x.dataset.v3Go==='combat'));if(cfg.id==='nans'&&native.dataset.tab===(cfg.combatTab||'combat'))document.querySelector('[data-combat-tab="attacks"]')?.click();}}});
host.addEventListener('click',e=>{const b=e.target.closest('[data-v3-go],[data-v3-social-go]');if(b)go(b.dataset.v3Go||b.dataset.v3SocialGo)});
let socialRollMode='normal';function roll(label,bonus){const a=Math.floor(Math.random()*20)+1,b=socialRollMode==='normal'?null:Math.floor(Math.random()*20)+1,n=b===null?a:socialRollMode==='adv'?Math.max(a,b):Math.min(a,b);const msg=`${label} : d20 ${b===null?a:a+' / '+b+' → '+n} ${bonus<0?'−':'+'} ${Math.abs(bonus)} = ${n+bonus}${n===1?' · 1 naturel':n===20?' · 20 naturel':''}`;let out=$('#v3-roll');out.textContent=msg;out.hidden=false;window.CompanionSocialDice?.show({label,dice:b===null?a:[a,b],bonus,total:n+bonus,mode:socialRollMode});try{window.CompanionV3Log?.(msg);}catch{} }
let socialPane='skills';
function renderSocial(){
 const s=cfg.social||{},abilities=s.abilities||{},saves=s.saves||{},skills=s.skills||{},extra=Array.isArray(s.extra)?s.extra:[];
 const groups={skills:['Compétences',skills],abilities:['Carac. & JdS',abilities],saves:['Jets de sauvegarde',saves]};
 const list=(values,kind)=>Object.entries(values).map(([name,bonus])=>'<button type="button" data-v3-roll="'+esc((kind==='saves'?'JdS ':'')+name)+'" data-bonus="'+Number(bonus)+'"><span><b>'+esc(name)+'</b>'+(kind==='abilities'&&s.scores?.[name]!==undefined?'<small>Score '+esc(s.scores[name])+'</small>':'')+'</span><strong>'+(bonus>=0?'+':'')+bonus+'</strong></button>').join('')||'<p class="v3-sub">Fiche à compléter depuis la source du personnage.</p>';
 $('#v3-social').innerHTML='<div class="v3-heading"><div><h2>Social · '+esc(cfg.name)+'</h2><p class="v3-sub">Jets de la fiche et informations utiles.</p></div></div>'+
 '<nav class="v3-sheet-tabs" aria-label="Profil social"><button type="button" data-v3-sheet="skills" class="'+(socialPane==='skills'?'active':'')+'">Compétences</button><button type="button" data-v3-sheet="abilities" class="'+(socialPane==='abilities'?'active':'')+'">Carac. & JdS</button><button type="button" data-v3-sheet="info" class="'+(socialPane==='info'?'active':'')+'">Infos utiles</button></nav>'+
 '<div class="v3-switch v3-social-mode"><button type="button" data-v3-social-mode="normal" class="'+(socialRollMode==='normal'?'active':'')+'">Normal</button><button type="button" data-v3-social-mode="adv" class="'+(socialRollMode==='adv'?'active':'')+'">Avantage</button><button type="button" data-v3-social-mode="dis" class="'+(socialRollMode==='dis'?'active':'')+'">Désavantage</button></div>'+
 (socialPane==='skills'?'<article class="v3-card"><h3>Compétences</h3><div class="v3-roll-grid">'+list(skills,'skills')+'</div></article>':socialPane==='abilities'?'<div class="v3-social-grid"><article class="v3-card"><h3>Caractéristiques</h3><div class="v3-roll-grid">'+list(abilities,'abilities')+'</div></article><article class="v3-card"><h3>Jets de sauvegarde</h3><div class="v3-roll-grid">'+list(saves,'saves')+'</div></article></div>':'<article class="v3-card"><h3>Informations utiles</h3><div class="v3-extra-grid">'+(extra.length?extra.map(([k,v])=>'<div><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>').join(''):'<div><small>Profil</small><b>Compétences et caractéristiques de la fiche actuelle.</b></div>')+'</div></article>')+
 '<div id="v3-roll" class="v3-result" role="status" hidden></div>';
}
$('#v3-social').addEventListener('click',e=>{const pane=e.target.closest('[data-v3-sheet]');if(pane){socialPane=pane.dataset.v3Sheet;renderSocial();return}const mode=e.target.closest('[data-v3-social-mode]');if(mode){socialRollMode=mode.dataset.v3SocialMode;renderSocial();return}const b=e.target.closest('[data-v3-roll]');if(b)roll(b.dataset.v3Roll,Number(b.dataset.bonus));});
const download=(name,body,type='application/json')=>{let url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)};
function exportAll(raw=false){if(raw){download(cfg.id+'-v3-brut.json',localStorage.getItem(key)||'{}');return;}const combat=localStorage.getItem(cfg.combatKey);download(cfg.id+'-companion-v3.json',JSON.stringify({format:'companion-v3-export',schema:1,character:cfg.id,surfaces:data,combatKey:cfg.combatKey,combat},null,2));}
function itemCard(i,index){let img=i.image&&(/^(https:\/\/|data:image\/)/).test(i.image)?`<img alt="" src="${esc(i.image)}" loading="lazy">`:`<span aria-hidden="true">${i.category==='consumable'?'◈':i.category==='equipment'?'⚔':'✦'}</span>`;return `<div class="v3-item"><div class="v3-item-icon">${img}</div><div class="v3-item-body"><b>${esc(i.name)}</b><small>${esc(i.category==='equipment'?'Équipement':i.category==='consumable'?'Consommable':'Objet divers')} · ×${i.qty}${i.attuned?' · Harmonisé':''}${i.active?' · Équipé':''}</small>${i.note?`<p>${esc(i.note)}</p>`:''}</div><button type="button" data-v3-edit="${index}" aria-label="Modifier ${esc(i.name)}">Modifier</button></div>`;}
function renderItems(){const el=$('#v3-inventory');el.innerHTML=`<div class="v3-heading"><div><h2>Inventaire · ${esc(cfg.name)}</h2><p class="v3-sub">${data.items.filter(i=>i.attuned).length}/3 harmonisations</p></div><div class="v3-actions"><button type="button" data-v3-add>+ Objet</button><button type="button" data-v3-undo ${lastTransaction?'':'disabled'}>↶ Annuler</button></div></div><div class="v3-switch"><button type="button" data-v3-category="equipment">Équipement</button><button type="button" data-v3-category="misc">Objets et consommables</button></div><div id="v3-item-list"></div><form id="v3-item-form" class="v3-card" hidden><h3>Objet</h3><label>Nom <input name="name" required maxlength="160"></label><label>Catégorie <select name="category"><option value="equipment">Équipement</option><option value="misc">Objet divers</option><option value="consumable">Consommable</option></select></label><label>Quantité <input name="qty" type="number" min="0" max="9999" value="1" required></label><label>Image HTTPS <input name="image" type="url" placeholder="https://…"></label><button type="button" data-v3-image>Choisir une image locale</button><label>Notes <textarea name="note" rows="3" maxlength="5000"></textarea></label><label class="v3-check"><input name="active" type="checkbox"> Équipé ou actif</label><label class="v3-check"><input name="attuned" type="checkbox"> Harmonisé</label><div class="v3-actions"><button type="submit">Enregistrer</button><button type="button" data-v3-delete>Supprimer</button><button type="button" data-v3-cancel>Fermer</button></div></form><div class="v3-actions"><button type="button" data-v3-export>Exporter JSON</button><button type="button" data-v3-import>Importer JSON</button><button type="button" data-v3-restore>Restaurer copie</button>${blocked?'<button type="button" data-v3-raw>Export brut</button>':''}</div>`;showCategory(el.dataset.category||'equipment');}
function showCategory(category){let panel=$('#v3-inventory');panel.dataset.category=category;panel.querySelectorAll('[data-v3-category]').forEach(b=>b.classList.toggle('active',b.dataset.v3Category===category));let rows=data.items.map((i,n)=>({i,n})).filter(({i})=>category==='equipment'?i.category==='equipment':i.category!=='equipment');$('#v3-item-list').innerHTML=rows.length?rows.map(({i,n})=>itemCard(i,n)).join(''):'<p class="v3-empty">Aucun objet dans cette catégorie.</p>';}
let editIndex=-1,pendingImage='';$('#v3-inventory').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.v3Category){showCategory(b.dataset.v3Category);return;}if(b.hasAttribute('data-v3-undo')){undoLastTransaction();return;}if(b.hasAttribute('data-v3-export'))exportAll();if(b.hasAttribute('data-v3-raw'))exportAll(true);if(b.hasAttribute('data-v3-import'))$('#v3-file').click();if(b.hasAttribute('data-v3-restore'))restore();if(b.hasAttribute('data-v3-image'))$('#v3-image-file').click();if(b.hasAttribute('data-v3-cancel'))$('#v3-item-form').hidden=true;
 if(b.hasAttribute('data-v3-add')||b.hasAttribute('data-v3-edit')){editIndex=b.hasAttribute('data-v3-edit')?Number(b.dataset.v3Edit):-1;const i=data.items[editIndex]||{name:'',category:$('#v3-inventory').dataset.category,qty:1,image:'',note:'',active:false,attuned:false};let f=$('#v3-item-form');f.reset();for(let k of ['name','category','qty','note'])f.elements[k].value=i[k];f.elements.image.value=i.image.startsWith('data:')?'':i.image;pendingImage=i.image;f.elements.active.checked=!!i.active;f.elements.attuned.checked=!!i.attuned;f.querySelector('[data-v3-delete]').hidden=editIndex<0;f.hidden=false;f.scrollIntoView({block:'nearest'});}
 if(b.hasAttribute('data-v3-delete')&&editIndex>=0&&confirm('Supprimer cet objet ?')){const before=snapshotTransaction();data.items.splice(editIndex,1);persist();recordInventoryMutation(before);renderItems();}});
$('#v3-inventory').addEventListener('submit',e=>{e.preventDefault();let f=e.target,i={name:f.elements.name.value.trim(),category:f.elements.category.value,qty:Number(f.elements.qty.value),image:f.elements.image.value.trim()||pendingImage,note:f.elements.note.value,active:f.elements.active.checked,attuned:f.elements.attuned.checked};if(!i.name)return;if(i.attuned&&!data.items[editIndex]?.attuned&&data.items.filter(x=>x.attuned).length>=3){warn('Trois objets déjà harmonisés.');return;}if(!i.image.startsWith('https://')&&!i.image.startsWith('data:image/'))i.image='';const before=snapshotTransaction();if(editIndex<0)data.items.push(i);else data.items[editIndex]=i;persist();recordInventoryMutation(before);renderItems();});
$('#v3-image-file').addEventListener('change',e=>{let file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>250000){warn('Choisis une image de moins de 250 Ko.');return;}let reader=new FileReader();reader.onload=()=>{pendingImage=String(reader.result);warn('Image ajoutée. Enregistre l’objet.');};reader.readAsDataURL(file);e.target.value='';});
function renderNotes(){
 let mechanicalLog=document.getElementById('log'),el=$('#v3-notes');
 const tabs='<div class="v3-heading"><div><h2>Journal & notes · '+esc(cfg.name)+'</h2><p class="v3-sub">Journal mécanique automatique et carnet personnel persistant.</p></div><div class="v3-switch v3-note-switch"><button type="button" data-v3-note-tab="mechanical" class="'+(data.noteTab==='mechanical'?'active':'')+'">Journal mécanique</button><button type="button" data-v3-note-tab="notes" class="'+(data.noteTab==='notes'?'active':'')+'">Notes de session</button></div></div>';
 if(data.noteTab==='mechanical'){
  el.innerHTML=tabs+'<section class="v3-card"><div class="v3-heading"><div><h3>Historique automatique</h3></div><div class="v3-actions"><button type="button" data-v3-clear-log>Effacer</button><button type="button" data-v3-export>Exporter la partie</button></div></div><input type="search" id="v3-log-search" placeholder="Rechercher une action…" aria-label="Rechercher dans le journal"><div id="v3-log-slot"></div></section>';
  if(mechanicalLog){$('#v3-log-slot').appendChild(mechanicalLog);mechanicalLog.classList.add('open');}
 }else{
  el.innerHTML=tabs+'<section><label class="v3-note-label">Carnet personnel <textarea id="v3-note-text" placeholder="Écrire les événements de la session…"></textarea></label><button type="button" data-v3-preview>'+(data.preview?'Replier':'Déplier')+' l’aperçu</button><div id="v3-preview" class="v3-card v3-preview" '+(data.preview?'':'hidden')+'>'+esc(data.notes||'')+'</div><div class="v3-heading"><h3>Personnages rencontrés</h3><button type="button" data-v3-npc-add>+ PNJ</button></div><div id="v3-npcs">'+data.npcs.map((p,n)=>'<article class="v3-card v3-npc">'+(p.image&&/^https:\/\//.test(p.image)?'<img src="'+esc(p.image)+'" alt="">':'')+'<div><b>'+esc(p.name)+'</b><p>'+esc(p.note)+'</p></div><button type="button" data-v3-npc="'+n+'">Modifier</button></article>').join('')+'</div><div class="v3-actions"><button type="button" data-v3-export>Exporter la partie</button><button type="button" data-v3-import>Importer une partie</button></div></section>';
  const note=$('#v3-note-text');if(note)note.value=data.notes;
 }
}
$('#v3-notes').addEventListener('input',e=>{
 if(e.target.id==='v3-log-search'){document.querySelectorAll('#log .log-entry').forEach(row=>row.hidden=!row.textContent.toLocaleLowerCase('fr').includes(e.target.value.toLocaleLowerCase('fr')));}
 if(e.target.id==='v3-note-text'){data.notes=e.target.value;persist();let preview=$('#v3-preview');if(preview)preview.textContent=data.notes||'L’aperçu apparaîtra ici.';}
});
$('#v3-notes').addEventListener('click',e=>{
 let b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-v3-note-tab')){data.noteTab=b.dataset.v3NoteTab;persist();renderNotes();return;}
 if(b.hasAttribute('data-v3-clear-log')&&confirm('Effacer le journal mécanique ?')){document.getElementById('log').innerHTML='';window.CompanionV3State&&localStorage.setItem(cfg.combatKey,JSON.stringify({...JSON.parse(localStorage.getItem(cfg.combatKey)||'{}'),journal:''}));}
 if(b.hasAttribute('data-v3-preview')){data.preview=!data.preview;persist();let preview=$('#v3-preview');if(preview)preview.hidden=!data.preview;b.textContent=(data.preview?'Replier':'Déplier')+' l’aperçu';}
 if(b.hasAttribute('data-v3-export'))exportAll();
 if(b.hasAttribute('data-v3-import'))$('#v3-file').click();
 if(b.hasAttribute('data-v3-npc-add')||b.hasAttribute('data-v3-npc')){
  let n=b.hasAttribute('data-v3-npc')?Number(b.dataset.v3Npc):-1,old=data.npcs[n]||{name:'',note:'',image:''};let name=prompt('Nom du PNJ',old.name);if(name===null||!name.trim())return;let note=prompt('Informations et notes',old.note);if(note===null)return;let image=prompt('URL HTTPS de l’image (facultatif)',old.image);if(image===null)return;let npc={name:name.trim().slice(0,160),note:note.slice(0,5000),image:image.startsWith('https://')?image.slice(0,2000):''};if(n<0)data.npcs.push(npc);else data.npcs[n]=npc;persist();renderNotes();
 }
});
function readCombat(raw){if(raw===null)return;let x=JSON.parse(raw);if(!x||typeof x!=='object'||Array.isArray(x))throw Error('État de combat invalide.');
 let s=cfg.id==='nans'||cfg.id==='rufus'?x.state:x;
 if(cfg.id==='rufus'&&x.schema!==1||cfg.id==='samoth'&&x.schema!==3)throw Error('Schéma de combat incompatible.');
 if(!s||typeof s!=='object'||!Number.isFinite(s.hp)||s.hp<0||s.hp>1000||(!s.eco&&cfg.id!=='brackmard')||(cfg.id==='brackmard'&&!s.used))throw Error('Ressources de combat invalides.');
 if(cfg.id==='samoth'&&(!s.slots||!Array.isArray(s.journal)))throw Error('Emplacements ou journal invalides.');
 if(cfg.id==='brackmard'&&(!Array.isArray(s.log)||!Number.isFinite(s.sup)))throw Error('Supériorité ou journal invalides.');
 if(cfg.id==='nans'&&typeof x.journal!=='string')throw Error('Journal de combat invalide.');
 if(cfg.id==='rufus'&&!Array.isArray(x.log))throw Error('Journal de combat invalide.');} 
function restore(){let raw=localStorage.getItem(backup);if(!raw){warn('Aucune copie précédente.');return;}try{let x=JSON.parse(raw);validate(x.surfaces);readCombat(x.combat);if(!confirm('Restaurer la sauvegarde précédente et recharger ?'))return;replace(x);}catch(e){warn(e.message)}}
function replace(x){const previous={surfaces:data,combat:localStorage.getItem(cfg.combatKey)};try{localStorage.setItem(backup,JSON.stringify(previous));localStorage.setItem(key,JSON.stringify(x.surfaces));if(x.combat!==null)localStorage.setItem(cfg.combatKey,x.combat);else localStorage.removeItem(cfg.combatKey);blocked=false;location.reload();}catch{warn('Remplacement impossible. La copie précédente est conservée.');}}
$('#v3-file').addEventListener('change',async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>1500000)throw Error('Fichier trop volumineux.');let x=JSON.parse(await file.text());if(x.format!=='companion-v3-export'||x.schema!==1||x.character!==cfg.id||x.combatKey!==cfg.combatKey)throw Error('Ce fichier ne correspond pas à ce compagnon.');validate(x.surfaces);readCombat(x.combat);if(confirm('Remplacer la partie actuelle par cet import ? Une copie sera conservée.'))replace(x);}catch(err){warn(err.message)}e.target.value='';});
// The availability indicator is derived from the engine's current turn state.
function syncEconomy(){let st=window.CompanionV3State?.();if(!st)return;const eco=st.eco||st.used||{};
 const turn=st.round||st.turn||1;
 if(cfg.id!=='samoth'){
  let marker=$('#v3-movement');if(!marker){let bar=$('.turnbar');if(bar){marker=document.createElement('button');marker.type='button';marker.id='v3-movement';marker.className='v3-movement';bar.appendChild(marker)}}
  if(marker){if(!marker.dataset.v3Bound){marker.addEventListener('click',()=>{const currentTurn=window.CompanionV3State?.()?.round||window.CompanionV3State?.()?.turn||1;data.movement={turn:currentTurn,used:!(data.movement?.used&&data.movement.turn===currentTurn)};persist();syncEconomy()});marker.dataset.v3Bound='1';}if(data.movement?.turn!==turn)data.movement={turn,used:false};marker.textContent=data.movement.used?'Mouvement · utilisé':(cfg.id==='brackmard'?'Mouvement · 7,5 m':cfg.id==='nans'?'Mouvement · 12 m':'Mouvement · libre');marker.classList.toggle('used',data.movement.used);marker.setAttribute('aria-pressed',String(data.movement.used));}
 }
 let buttons=[];
 if(cfg.id==='samoth')buttons=[...document.querySelectorAll('.cast')].map(b=>[b,b.dataset.spell==='shield'||b.dataset.spell==='absorb'||b.dataset.spell==='counter'?'reaction':st.meta==='Accéléré'&&b.dataset.spell!=='shield'?'bonus':'action']);
 if(cfg.id==='brackmard')buttons=[...document.querySelectorAll('button[onclick]')].map(b=>{let c=b.getAttribute('onclick');let k=/secondWind|actionSurge|startBonusAttack|commandersStrike/.test(c)?'bonus':/reactionAttack|riposte/.test(c)?'reaction':/forgeBreath|dwarvenFortitude|dodgeOnly/.test(c)?'action':null;return[b,k]});
 if(cfg.id==='nans')buttons=[...document.querySelectorAll('button[onclick]')].map(b=>{let c=b.getAttribute('onclick');let k=/useCape\(/.test(c)?'reaction':/capeSilence\(|useBark\(|transferEnergy\(|toggleWeaponMode\(|hornPower\('rally'/.test(c)?'bonus':/hornPower\(|chargedImpact\(|intimidate\(/.test(c)?'action':null;return[b,k]});
 if(cfg.id==='rufus')buttons=[...document.querySelectorAll('button[onclick]')].map(b=>{let c=b.getAttribute('onclick');let k=/reaction\(|useCape\(/.test(c)?'reaction':/cunning\(|psiTeleport\(|reconstitute\(|attackKind\('psi2'/.test(c)?'bonus':/attackKind\(|daily\(|whispers\(/.test(c)?'action':null;return[b,k]});
 for(const [b,k] of buttons){if(!k||!b.isConnected)continue;let used=!!eco[k];if(cfg.id==='brackmard'&&k==='action'&&st.extraAction)used=false;if(cfg.id==='samoth'&&st.phase==='dragon'&&k!=='reaction')used=true;if(used)b.disabled=true;else if(b.classList.contains('v3-unavailable'))b.disabled=false;b.classList.toggle('v3-unavailable',used);b.setAttribute('aria-disabled',String(used));}
}
const undoAdapter=window.CompanionV3UndoAdapter;
let transactionStart=null,lastTransaction=null;let undoLastTransaction=()=>false;
function snapshotTransaction(){return JSON.stringify({combat:undoAdapter?.snapshot()??null,surfaces:structuredClone(data)})}
function restoreTransaction(raw){const x=JSON.parse(raw);if(x.combat!==null)undoAdapter.restore(x.combat);data=validate(x.surfaces);lastTransaction=null;transactionStart=null;persist();renderItems();if(!$('#v3-notes').hidden)renderNotes();const button=$('#v3-undo');if(button)button.disabled=true;syncEconomy()}
function recordInventoryMutation(before){if(!undoAdapter)return;lastTransaction=before;const button=$('#v3-undo');if(button)button.disabled=false;}
if(undoAdapter){let bar=$('.turnbar');if(bar){let u=document.createElement('button');u.type='button';u.id='v3-undo';u.textContent='↶ Annuler';u.disabled=true;u.setAttribute('aria-label','Annuler la dernière opération mécanique');bar.appendChild(u);undoLastTransaction=()=>{if(!lastTransaction)return false;try{restoreTransaction(lastTransaction);return true}catch(e){warn('Annulation impossible : '+e.message);return false}};u.addEventListener('click',undoLastTransaction)}
 document.addEventListener('click',e=>{if(e.target.closest('#v3-root,#v3-undo,nav.tabs'))return;const target=e.target.closest('button,input,select');if(!target)return;
 if(transactionStart===null)transactionStart=snapshotTransaction();
 setTimeout(()=>{if(transactionStart===null||undoAdapter.pending())return;let after=snapshotTransaction();if(after!==transactionStart){lastTransaction=transactionStart;$('#v3-undo').disabled=false;}transactionStart=null;syncEconomy()},70);
 },true);
 document.addEventListener('change',e=>{if(e.target.closest('#v3-root'))return;let before=snapshotTransaction();setTimeout(()=>{if(undoAdapter.pending())return;let after=snapshotTransaction();if(after!==before){lastTransaction=before;$('#v3-undo').disabled=false;}syncEconomy()},70)},true);
}
document.addEventListener('click',()=>setTimeout(syncEconomy,0));document.addEventListener('change',()=>setTimeout(syncEconomy,0));
window.CompanionV3={key,exportAll,go,syncEconomy,undo:undoLastTransaction,snapshot:snapshotTransaction,restore:restoreTransaction,
 getItems:()=>structuredClone(data.items),
 addItem:item=>{const i={id:crypto.randomUUID(),name:String(item?.name||'Objet').slice(0,160),category:item?.category==='equipment'?'equipment':'misc',qty:Math.min(9999,Math.max(0,Math.floor(Number(item?.qty??1)))),note:String(item?.note||'').slice(0,5000),image:'',active:false,attuned:false};const before=snapshotTransaction();data.items.push(i);persist();recordInventoryMutation(before);renderItems();return structuredClone(i)},
 updateItem:item=>{const i=data.items.find(x=>x.id===item?.id||x.name===item?.id);if(!i)throw Error('Objet inconnu');const before=snapshotTransaction();if(item.qty!==undefined)i.qty=Math.min(9999,Math.max(0,Math.floor(Number(item.qty))));if(item.note!==undefined)i.note=String(item.note).slice(0,5000);persist();recordInventoryMutation(before);renderItems();return structuredClone(i)},
 removeItem:id=>{const count=data.items.length,prior=snapshotTransaction();data.items=data.items.filter(x=>x.id!==id&&x.name!==id);if(count===data.items.length)throw Error('Objet inconnu');persist();recordInventoryMutation(prior);renderItems();return true},
 clearAll(){localStorage.removeItem(key);localStorage.removeItem(backup)}};go(cfg.combatTab||'combat');syncEconomy();
})();
